import { User, Workspace, Project, Task, Team, Repository, NotificationItem } from '../types';

export const MOCK_USER: User = {
  id: 'u-1',
  name: 'Alex Vance',
  email: 'alex.vance@taskflow.ai',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80',
  role: 'owner',
  jobTitle: 'Principal Software Architect',
  department: 'Engineering',
  status: 'online',
};

export const MOCK_MEMBERS: User[] = [
  MOCK_USER,
  {
    id: 'u-2',
    name: 'Sarah Chen',
    email: 'sarah.c@taskflow.ai',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=250&q=80',
    role: 'admin',
    jobTitle: 'Staff Backend Engineer',
    department: 'Engineering',
    status: 'online',
  },
  {
    id: 'u-3',
    name: 'Marcus Brody',
    email: 'marcus.b@taskflow.ai',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=250&q=80',
    role: 'member',
    jobTitle: 'Lead Product Designer',
    department: 'Design',
    status: 'busy',
  },
  {
    id: 'u-4',
    name: 'Elena Rostova',
    email: 'elena.r@taskflow.ai',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=250&q=80',
    role: 'member',
    jobTitle: 'DevOps & Cloud Engineer',
    department: 'DevOps',
    status: 'online',
  },
  {
    id: 'u-5',
    name: 'David Kim',
    email: 'david.k@taskflow.ai',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=250&q=80',
    role: 'member',
    jobTitle: 'Frontend Architect',
    department: 'Engineering',
    status: 'offline',
  },
];

export const MOCK_WORKSPACES: Workspace[] = [
  {
    id: 'ws-1',
    name: 'Acme Global Cloud',
    slug: 'acme-global',
    plan: 'Enterprise',
    membersCount: 128,
  },
  {
    id: 'ws-2',
    name: 'Nexus Labs Product',
    slug: 'nexus-labs',
    plan: 'Pro',
    membersCount: 42,
  },
  {
    id: 'ws-3',
    name: 'Personal Sandbox',
    slug: 'sandbox',
    plan: 'Starter',
    membersCount: 1,
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    projectKey: 'ENG',
    name: 'Core API Platform v3.0',
    description: 'High-throughput microservices architecture migration to Cloud Run & Kubernetes.',
    icon: 'server',
    workspace: { id: 'ws-eng-001', name: 'Engineering Workspace', slug: 'engineering' },
    organization: { id: 'org-default', name: 'Acme Corp', slug: 'acme-corp' },
    owner: { id: MOCK_MEMBERS[1].id, name: MOCK_MEMBERS[1].name, email: MOCK_MEMBERS[1].email, avatar: MOCK_MEMBERS[1].avatar },
    visibility: 'workspace',
    status: 'active',
    repositoryUrl: 'https://github.com/acme-corp/core-api',
    websiteUrl: 'https://docs.acme.com',
    startDate: '2026-01-15',
    endDate: '2026-09-30',
    isArchived: false,
    isFavorite: true,
    isPinned: true,
    progress: 68,
    taskCount: { total: 42, completed: 28, inProgress: 14 },
    memberCount: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'proj-2',
    projectKey: 'DSN',
    name: 'TaskFlow Design System 2.0',
    description: 'Unified component library with Tailwind CSS v4, dark mode tokens & accessibility AA compliance.',
    icon: 'palette',
    workspace: { id: 'ws-prod-002', name: 'Product Design Workspace', slug: 'product-design' },
    organization: { id: 'org-default', name: 'Acme Corp', slug: 'acme-corp' },
    owner: { id: MOCK_MEMBERS[2].id, name: MOCK_MEMBERS[2].name, email: MOCK_MEMBERS[2].email, avatar: MOCK_MEMBERS[2].avatar },
    visibility: 'organization',
    status: 'active',
    repositoryUrl: 'https://github.com/acme-corp/design-system',
    websiteUrl: 'https://design.acme.com',
    startDate: '2026-02-01',
    endDate: '2026-08-20',
    isArchived: false,
    isFavorite: true,
    isPinned: false,
    progress: 85,
    taskCount: { total: 24, completed: 20, inProgress: 4 },
    memberCount: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'proj-3',
    projectKey: 'OPS',
    name: 'SOC2 Type II Compliance & Audit',
    description: 'Security hardening, automated audit logging, IAM role least privilege verification.',
    icon: 'shield',
    workspace: { id: 'ws-ops-004', name: 'Operations & Security', slug: 'operations' },
    organization: { id: 'org-default', name: 'Acme Corp', slug: 'acme-corp' },
    owner: { id: MOCK_MEMBERS[3].id, name: MOCK_MEMBERS[3].name, email: MOCK_MEMBERS[3].email, avatar: MOCK_MEMBERS[3].avatar },
    visibility: 'private',
    status: 'planning',
    repositoryUrl: '',
    websiteUrl: '',
    startDate: '2026-04-01',
    endDate: '2026-11-15',
    isArchived: false,
    isFavorite: false,
    isPinned: false,
    progress: 35,
    taskCount: { total: 18, completed: 6, inProgress: 12 },
    memberCount: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'proj-4',
    projectKey: 'AI',
    name: 'GenAI Automated Sprint Summarizer',
    description: 'Integrating Gemini Pro 1.5 & Live API for real-time release note synthesis.',
    icon: 'zap',
    workspace: { id: 'ws-eng-001', name: 'Engineering Workspace', slug: 'engineering' },
    organization: { id: 'org-default', name: 'Acme Corp', slug: 'acme-corp' },
    owner: { id: MOCK_USER.id, name: MOCK_USER.name, email: MOCK_USER.email, avatar: MOCK_USER.avatar },
    visibility: 'workspace',
    status: 'active',
    repositoryUrl: 'https://github.com/acme-corp/sprint-ai',
    websiteUrl: 'https://ai.acme.com',
    startDate: '2026-05-01',
    endDate: '2026-10-01',
    isArchived: false,
    isFavorite: false,
    isPinned: true,
    progress: 45,
    taskCount: { total: 31, completed: 14, inProgress: 17 },
    memberCount: 5,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: 'task-1',
    taskKey: 'ENG-101',
    title: 'Migrate legacy Redis caching layer to Redis Cluster with multi-region replication',
    description: 'We need to upgrade our single-node Redis instance to a multi-region cluster to prevent single-point-of-failure under peak loads.',
    status: 'In Progress',
    priority: 'Urgent',
    type: 'Feature',
    project: { id: 'proj-1', name: 'Core API Platform v3.0', projectKey: 'ENG' },
    workspace: { id: 'ws-eng-001', name: 'Engineering Workspace' },
    organization: { id: 'org-default', name: 'Acme Corp' },
    projectId: 'proj-1',
    projectKey: 'ENG',
    projectName: 'Core API Platform v3.0',
    assignee: MOCK_MEMBERS[1],
    reporter: MOCK_USER,
    labels: ['backend', 'database', 'infrastructure'],
    dueDate: '2026-08-15',
    estimatedHours: 16,
    spentHours: 8,
    storyPoints: 8,
    watchers: ['u-1', 'u-2'],
    isFavorite: true,
    isWatching: true,
    isArchived: false,
    createdAt: '2026-08-01T10:00:00.000Z',
    updatedAt: '2026-08-07T12:00:00.000Z',
    commentsCount: 5,
    subtaskCount: { total: 4, done: 3 },
  },
  {
    id: 'task-2',
    taskKey: 'ENG-102',
    title: 'Fix race condition in JWT token refresh endpoint under high concurrent requests',
    description: 'Multiple simultaneous refresh requests cause token invalidation errors on the mobile client.',
    status: 'In Review',
    priority: 'High',
    type: 'Bug',
    project: { id: 'proj-1', name: 'Core API Platform v3.0', projectKey: 'ENG' },
    workspace: { id: 'ws-eng-001', name: 'Engineering Workspace' },
    organization: { id: 'org-default', name: 'Acme Corp' },
    projectId: 'proj-1',
    projectKey: 'ENG',
    projectName: 'Core API Platform v3.0',
    assignee: MOCK_USER,
    reporter: MOCK_MEMBERS[1],
    labels: ['security', 'auth', 'bugfix'],
    dueDate: '2026-08-10',
    estimatedHours: 8,
    spentHours: 6,
    storyPoints: 5,
    watchers: ['u-1'],
    isFavorite: false,
    isWatching: true,
    isArchived: false,
    createdAt: '2026-08-03T14:30:00.000Z',
    updatedAt: '2026-08-07T14:00:00.000Z',
    commentsCount: 8,
    subtaskCount: { total: 2, done: 2 },
  },
  {
    id: 'task-3',
    taskKey: 'DSN-204',
    title: 'Design accessible dark mode contrast system for charts and analytics graphs',
    description: 'Ensure all chart palettes satisfy WCAG 2.1 AA 4.5:1 minimum contrast ratio against dark backgrounds.',
    status: 'Done',
    priority: 'Medium',
    type: 'Improvement',
    project: { id: 'proj-2', name: 'TaskFlow Design System 2.0', projectKey: 'DSN' },
    workspace: { id: 'ws-eng-001', name: 'Engineering Workspace' },
    organization: { id: 'org-default', name: 'Acme Corp' },
    projectId: 'proj-2',
    projectKey: 'DSN',
    projectName: 'TaskFlow Design System 2.0',
    assignee: MOCK_MEMBERS[2],
    reporter: MOCK_USER,
    labels: ['a11y', 'ui-ux', 'tokens'],
    dueDate: '2026-08-05',
    estimatedHours: 12,
    spentHours: 12,
    storyPoints: 3,
    watchers: [],
    isFavorite: true,
    isWatching: false,
    isArchived: false,
    createdAt: '2026-07-28T09:00:00.000Z',
    updatedAt: '2026-08-06T16:00:00.000Z',
    commentsCount: 3,
    subtaskCount: { total: 3, done: 3 },
  },
  {
    id: 'task-4',
    taskKey: 'AI-301',
    title: 'Implement streaming Gemini response handler for real-time task generation',
    description: 'Set up Server-Sent Events (SSE) route to stream AI generated user stories directly into the queue.',
    status: 'In Progress',
    priority: 'High',
    type: 'Epic',
    project: { id: 'proj-4', name: 'GenAI Automated Sprint Summarizer', projectKey: 'AI' },
    workspace: { id: 'ws-eng-001', name: 'Engineering Workspace' },
    organization: { id: 'org-default', name: 'Acme Corp' },
    projectId: 'proj-4',
    projectKey: 'AI',
    projectName: 'GenAI Automated Sprint Summarizer',
    assignee: MOCK_MEMBERS[4],
    reporter: MOCK_USER,
    labels: ['ai', 'gemini', 'streaming'],
    dueDate: '2026-08-22',
    estimatedHours: 24,
    spentHours: 10,
    storyPoints: 13,
    watchers: ['u-1', 'u-4', 'u-5'],
    isFavorite: false,
    isWatching: true,
    isArchived: false,
    createdAt: '2026-08-04T11:20:00.000Z',
    updatedAt: '2026-08-07T15:45:00.000Z',
    commentsCount: 12,
    subtaskCount: { total: 6, done: 4 },
  },
  {
    id: 'task-5',
    taskKey: 'OPS-402',
    title: 'Configure automated Terraform cloud drift detection & slack alert webhooks',
    description: 'Set up daily cron pipeline checking for manual GCP/AWS infrastructure changes.',
    status: 'Todo',
    priority: 'Medium',
    type: 'Task',
    project: { id: 'proj-3', name: 'SOC2 Type II Compliance & Audit', projectKey: 'OPS' },
    workspace: { id: 'ws-eng-001', name: 'Engineering Workspace' },
    organization: { id: 'org-default', name: 'Acme Corp' },
    projectId: 'proj-3',
    projectKey: 'OPS',
    projectName: 'SOC2 Type II Compliance & Audit',
    assignee: MOCK_MEMBERS[3],
    reporter: MOCK_MEMBERS[1],
    labels: ['devops', 'terraform', 'security'],
    dueDate: '2026-08-28',
    estimatedHours: 10,
    spentHours: 0,
    storyPoints: 5,
    watchers: [],
    isFavorite: false,
    isWatching: false,
    isArchived: false,
    createdAt: '2026-08-06T15:00:00.000Z',
    updatedAt: '2026-08-06T15:00:00.000Z',
    commentsCount: 1,
    subtaskCount: { total: 3, done: 0 },
  },
  {
    id: 'task-6',
    taskKey: 'ENG-105',
    title: 'Add support for custom webhooks on task creation and status changes',
    description: 'Provide outgoing webhook payload dispatcher with HMAC-SHA256 signature validation.',
    status: 'Backlog',
    priority: 'Low',
    type: 'Feature',
    project: { id: 'proj-1', name: 'Core API Platform v3.0', projectKey: 'ENG' },
    workspace: { id: 'ws-eng-001', name: 'Engineering Workspace' },
    organization: { id: 'org-default', name: 'Acme Corp' },
    projectId: 'proj-1',
    projectKey: 'ENG',
    projectName: 'Core API Platform v3.0',
    assignee: undefined,
    reporter: MOCK_USER,
    labels: ['api', 'integrations'],
    dueDate: '2026-09-10',
    estimatedHours: 14,
    spentHours: 0,
    storyPoints: 8,
    watchers: [],
    isFavorite: false,
    isWatching: false,
    isArchived: false,
    createdAt: '2026-08-06T16:00:00.000Z',
    updatedAt: '2026-08-06T16:00:00.000Z',
    commentsCount: 0,
    subtaskCount: { total: 2, done: 0 },
  },
];

export const MOCK_REPOSITORIES: Repository[] = [
  {
    id: 'repo-1',
    name: 'taskflow-core-api',
    description: 'Enterprise Go & Node.js backend microservices engine.',
    visibility: 'private',
    stars: 142,
    forks: 38,
    language: 'TypeScript',
    defaultBranch: 'main',
    updatedAt: '5 mins ago',
    pipelineStatus: 'success',
    pullRequests: [
      {
        id: 'pr-1',
        number: 402,
        title: 'feat(auth): Add PKCE OAuth2 support for native desktop client',
        author: MOCK_MEMBERS[1],
        status: 'open',
        branch: 'feat/pkce-oauth',
        baseBranch: 'main',
        commentsCount: 4,
        createdAt: '2 hours ago',
      },
      {
        id: 'pr-2',
        number: 398,
        title: 'fix(cache): resolve race condition in distributed lock manager',
        author: MOCK_USER,
        status: 'open',
        branch: 'fix/dist-lock',
        baseBranch: 'main',
        commentsCount: 9,
        createdAt: 'Yesterday',
      },
    ],
  },
  {
    id: 'repo-2',
    name: 'taskflow-ui-components',
    description: 'Design system, React 19 UI component library & Tailwind styling.',
    visibility: 'internal',
    stars: 89,
    forks: 14,
    language: 'TypeScript',
    defaultBranch: 'main',
    updatedAt: '12 mins ago',
    pipelineStatus: 'running',
    pullRequests: [
      {
        id: 'pr-3',
        number: 115,
        title: 'style(theme): implement dark mode glassmorphism elevation layers',
        author: MOCK_MEMBERS[2],
        status: 'open',
        branch: 'style/dark-elevation',
        baseBranch: 'main',
        commentsCount: 2,
        createdAt: '3 hours ago',
      },
    ],
  },
];

export const MOCK_TEAMS: Team[] = [
  {
    id: 'team-1',
    name: 'Core Systems Architecture',
    description: 'Responsible for backend infrastructure, scalability, API gateways and database clusters.',
    lead: MOCK_USER,
    members: [
      { ...MOCK_MEMBERS[0], assignedTasksCount: 6, weeklyWorkloadHrs: 38 },
      { ...MOCK_MEMBERS[1], assignedTasksCount: 8, weeklyWorkloadHrs: 42 },
      { ...MOCK_MEMBERS[3], assignedTasksCount: 4, weeklyWorkloadHrs: 32 },
    ],
    projectsCount: 3,
  },
  {
    id: 'team-2',
    name: 'Product Design & UX',
    description: 'Crafting pixel-perfect user journeys, accessibility, and high performance component libraries.',
    lead: MOCK_MEMBERS[2],
    members: [
      { ...MOCK_MEMBERS[2], assignedTasksCount: 5, weeklyWorkloadHrs: 35 },
      { ...MOCK_MEMBERS[4], assignedTasksCount: 7, weeklyWorkloadHrs: 40 },
    ],
    projectsCount: 2,
  },
];

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'Pull Request Review Required',
    message: 'Sarah Chen requested your review on PR #402 "feat(auth): Add PKCE OAuth2 support".',
    type: 'mention',
    read: false,
    createdAt: '10 minutes ago',
    actor: MOCK_MEMBERS[1],
  },
  {
    id: 'notif-2',
    title: 'High Priority Task Assigned',
    message: 'Marcus Brody assigned you to DSN-204 "Design accessible dark mode contrast system".',
    type: 'assignment',
    read: false,
    createdAt: '1 hour ago',
    actor: MOCK_MEMBERS[2],
  },
  {
    id: 'notif-3',
    title: 'CI/CD Pipeline Succeeded',
    message: 'Build #8921 on taskflow-core-api (main branch) passed all 342 integration tests.',
    type: 'system',
    read: true,
    createdAt: '3 hours ago',
  },
  {
    id: 'notif-4',
    title: 'Sprint 24 Planning Completed',
    message: 'Sprint velocity target set to 84 story points for the upcoming 2-week cycle.',
    type: 'status_change',
    read: true,
    createdAt: 'Yesterday',
  },
];
