import { Router } from 'express';
import healthRoutes from './health.routes';
import authRoutes from './auth.routes';
import userRoutes from './user.routes';
import organizationRoutes from './organization.routes';
import inviteRoutes from './invite.routes';
import projectRoutes from './project.routes';
import taskRoutes from './task.routes';
import commentRoutes from './comment.routes';
import attachmentRoutes from './attachment.routes';
import roleRoutes from './role.routes';
import permissionRoutes from './permission.routes';
import workspaceRoutes from './workspace.routes';
import activityRoutes from './activity.routes';
import boardRoutes from './board.routes';
import sprintRoutes from './sprint.routes';
import calendarRoutes from './calendar.routes';
import releaseRoutes from './release.routes';
import roadmapRoutes from './roadmap.routes';
import notificationRoutes from './notification.routes';
import reportsRoutes from './reports.routes';
import timeEntryRoutes from './timeEntry.routes';
import workloadRoutes from './workload.routes';
import searchRoutes from './search.routes';
import emailRoutes from './email.routes';
import githubIntegrationRoutes from './githubIntegration.routes';
import workAssignmentRoutes from './workAssignment.routes';

const router = Router();

router.use('/health', healthRoutes);
router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/organizations', organizationRoutes);
router.use('/workspaces', workspaceRoutes);
router.use('/invitations', inviteRoutes);
router.use('/projects', projectRoutes);
router.use('/tasks', taskRoutes);
router.use('/work-assignments', workAssignmentRoutes);
router.use('/assignments', workAssignmentRoutes);
router.use('/comments', commentRoutes);
router.use('/attachments', attachmentRoutes);
router.use('/roles', roleRoutes);
router.use('/permissions', permissionRoutes);
router.use('/activity', activityRoutes);
router.use('/boards', boardRoutes);
router.use('/sprints', sprintRoutes);
router.use('/calendar', calendarRoutes);
router.use('/releases', releaseRoutes);
router.use('/roadmap', roadmapRoutes);
router.use('/notifications', notificationRoutes);
router.use('/reports', reportsRoutes);
router.use('/time-entries', timeEntryRoutes);
router.use('/workload', workloadRoutes);
router.use('/search', searchRoutes);
router.use('/email', emailRoutes);
router.use('/integrations/github', githubIntegrationRoutes);
router.use('/github', githubIntegrationRoutes);

export default router;

